#!/bin/bash

# 准备参数列表
PARAMS=""
DOCKER_CMD_ARGS="" # 用于存储 Docker 命令的额外参数

# 如果有参数传入，则处理参数
if [ $# -gt 0 ]; then
    # 检查第一个参数是否是 --up
    if [ "$1" == "--up" ]; then
        DOCKER_CMD_ARGS="--entrypoint python"
        PARAMS="/Upload-Assistant/config-generator.py"
        # 移除 --up 参数，以便后续不再处理
        shift
    elif [ -d "$1" ]; then
        # 获取第一个参数的完整绝对路径
        FIRST_ARG=$(readlink -f "$1")

        # 重新构建参数列表，将完整路径作为第一个参数
        PARAMS="$FIRST_ARG ${@:2}"
    else
        # 如果不是文件夹，直接使用原始参数
        PARAMS="$*"
    fi
fi

# 执行 Docker 命令
docker run --rm -it --privileged --network=host \
    -v /root/docker/ua/config.py:/Upload-Assistant/data/config.py \
    -v /root/docker/ua/tmp:/Upload-Assistant/tmp \
    -v /root/qb/up:/root/qb/up \
    -v /root/qBittorrent/data/BT_backup:/BT_backup \
    $DOCKER_CMD_ARGS \
    ghcr.io/audionut/upload-assistant:latest $PARAMS